ProductBookinUI/ProductBookinUI/Controllers/AirController.cs
using ProductBookinUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Sockets;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using System.Text;

namespace ProductBookinUI.Controllers
{
    public class AirController : Controller
    {
        public ActionResult GetAirProducts()
        {
            List<AirProduct> list = GetAirProductsList();

            return View(list);
        }

        public List<AirProduct> GetAirProductsList()
        {
            string url = "http://localhost:49896";
            List<AirProduct> airProduct = new List<AirProduct>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Air").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string AirProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<AirProduct>>(AirProductResponse);

                }
            }
            return airProduct;
        }

        //Insert
        public List<AirProduct> AddProductIntoDB(AirProduct airProduct)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                airProduct.isBooked = false;
                airProduct.isSaved = false;
                var httpContent = new StringContent(JsonConvert.SerializeObject(airProduct), Encoding.UTF8, "application/json");

                HttpResponseMessage response = client.PostAsync("/api/Air", httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<AirProduct>>(ProductResponse);

                }
            }
            return null;
        }

        public ActionResult AddAirProduct()
        {
            return View();
        }

        public List<AirProduct> SaveProductIntoDB(int productId)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var httpContent = new StringContent(JsonConvert.SerializeObject(productId), Encoding.UTF8, "application/json");

                List<AirProduct> list = GetAirProductsList();
                AirProduct dummy = list.Find(item => item.Id == productId);
                if (dummy.isSaved == true)
                    ViewData["CantSave"] = "true";
                HttpResponseMessage response = client.PutAsync("/api/Air/Save/" + productId, httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                      JsonConvert.DeserializeObject<List<AirProduct>>(ProductResponse);

                }
                HttpResponseMessage response1 = client.GetAsync("/api/Air").Result;
                if (response1.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response1.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<AirProduct>>(ProductResponse);
                }
            }
            return null;
        }

        public ActionResult OnBookClick(int productId)
        {
            List<AirProduct> list = BookProductIntoDB(productId);
            return View(list);
        }

        public ActionResult OnSaveClick(int productId)
        {
            List<AirProduct> list = SaveProductIntoDB(productId);
            return View(list);
        }

        public List<AirProduct> BookProductIntoDB(int productId)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var httpContent = new StringContent(JsonConvert.SerializeObject(productId), Encoding.UTF8, "application/json");

                List<AirProduct> list = GetAirProductsList();
                AirProduct dummy = list.Find(item => item.Id == productId);
                if (dummy.isBooked == true)
                    ViewData["CantBook"] = "true";

                HttpResponseMessage response = client.PutAsync("/api/Air/Book/" + productId, httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                      JsonConvert.DeserializeObject<List<AirProduct>>(ProductResponse);

                }
                HttpResponseMessage response1 = client.GetAsync("/api/Air").Result;
                if (response1.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response1.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<AirProduct>>(ProductResponse);
                }
            }
            return null;
        }

        public ActionResult GetSavedProds()
        {
            List<AirProduct> list = GetSavedProducts();
            return View(list);
        }

        public List<AirProduct> GetSavedProducts()
        {
            string url = "http://localhost:49896";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Air/GetSavedItems").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string  ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<AirProduct>>( ProductResponse);
                }
            }
            return null;

        }

        public ActionResult GetBookedProds()
        {
            List<AirProduct> list = GetBookedProducts();
            return View(list);
        }
        public List<AirProduct> GetBookedProducts()
        {
            string url = "http://localhost:49896";


            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Air/GetBookedItems").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<AirProduct>>(ProductResponse);
                }
            }
            return null;

        }
    }
}

ProductBookinUI/ProductBookinUI/Views/Air/AddAirProduct.cshtml
@model ProductBookinUI.Models.AirProduct

@{
    ViewBag.Title = "AddAirProduct";
}

<h2>AddAirProduct</h2>

@using (Html.BeginForm("AddProductIntoDB", "Air", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AirProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FlightCompany, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FlightCompany, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FlightCompany, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivalDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArrivalDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromPlace, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FromPlace, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToPlace, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToPlace, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProductBookinUI/ProductBookinUI/Views/Air/GetAirProducts.cshtml
@model IEnumerable<ProductBookinUI.Models.AirProduct>

@{
    ViewBag.Title = "GetAirProducts";
}

<h2>GetAirProducts</h2>

<p>
    @Html.ActionLink("Get Saved Items", "GetSavedProds")
</p>
<p>@Html.ActionLink("Get Booked Items", "GetBookedProds")</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FlightCompany)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FlightCompany)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartureDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArrivalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
       
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id })
            
        </td>
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Air/GetBookedProds.cshtml
@model IEnumerable<ProductBookinUI.Models.AirProduct>

@{
    ViewBag.Title = "GetBookedProds";
}

<h2>GetBookedProds</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FlightCompany)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th> 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FlightCompany)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartureDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArrivalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td> 
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Air/GetSavedProds.cshtml
@model IEnumerable<ProductBookinUI.Models.AirProduct>

@{
    ViewBag.Title = "GetSavedProds";
}

<h2>GetSavedProds</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FlightCompany)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th> 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FlightCompany)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartureDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArrivalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td> 
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Air/OnBookClick.cshtml
@model IEnumerable<ProductBookinUI.Models.AirProduct>

@{
    ViewBag.Title = "OnBookClick";
}

<h2>OnBookClick</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FlightCompany)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isBooked)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isSaved)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FlightCompany)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartureDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArrivalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isBooked)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isSaved)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
@if (ViewData["CantBook"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("Cant book");
        };
    </script>
}

ProductBookinUI/ProductBookinUI/Views/Air/OnSaveClick.cshtml
@model IEnumerable<ProductBookinUI.Models.AirProduct>

@{
    ViewBag.Title = "OnSaveClick";
}

<h2>OnSaveClick</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FlightCompany)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
     
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FlightCompany)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartureDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArrivalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToPlace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
       
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id })
        </td>
    </tr>
}

</table>
@if (ViewData["CantSave"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("Cant book");
        };
    </script>
}