ProductBookinUI/ProductBookinUI/Controllers/ActivityController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ProductBookinUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ProductBookinUI.Controllers
{
    public class ActivityController : Controller
    {
        // GET: Activity
        public ActionResult GetActivityProducts()
        {
            List<ActivityProduct> list = GetActivityProductsList();

            return View(list);
        }

        public List<ActivityProduct> GetActivityProductsList()
        {
            string url = "http://localhost:49896";

            List<ActivityProduct> activityProduct = new List<ActivityProduct>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Activity").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);

                }
            }
            return activityProduct;
        }

        //Insert
        public List<ActivityProduct> AddProductIntoDB(ActivityProduct activityProduct)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                activityProduct.isBooked = false;
                activityProduct.isSaved = false;
                var httpContent = new StringContent(JsonConvert.SerializeObject(activityProduct), Encoding.UTF8, "application/json");

                HttpResponseMessage response = client.PostAsync("/api/Activity", httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);

                }
            }
            return null;
        }

        public ActionResult AddActivityProduct()
        {
            return View();
        }

        public List<ActivityProduct> SaveProductIntoDB(int productId)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var httpContent = new StringContent(JsonConvert.SerializeObject(productId), Encoding.UTF8, "application/json");

                List<ActivityProduct> list = GetActivityProductsList();

                ActivityProduct dummy = list.Find(item => item.Id == productId);
                if (dummy.isBooked == true)
                    ViewData["CantSave"] = "true";

                HttpResponseMessage response = client.PutAsync("/api/Activity/Save/" + productId, httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);
                }

                HttpResponseMessage response1 = client.GetAsync("/api/Activity").Result;
                if (response1.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response1.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);
                }
            }
            return null;
        }

        public List<ActivityProduct> BookProductIntoDB(int productId)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var httpContent = new StringContent(JsonConvert.SerializeObject(productId), Encoding.UTF8, "application/json");

                List<ActivityProduct> list = GetActivityProductsList();
                ActivityProduct dummy = list.Find(item => item.Id == productId);
                if (dummy.isBooked == true)
                    ViewData["CantBook"] = "true";

                HttpResponseMessage response = client.PutAsync("/api/Activity/Book/" + productId, httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);
                }
                HttpResponseMessage response1 = client.GetAsync("/api/Activity").Result;
                if (response1.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response1.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);
                }
            }
            return null;
        }

        public ActionResult OnBookClick(int productId)
        {
            List<ActivityProduct> list = BookProductIntoDB(productId);
            return View(list);
        }

        public ActionResult OnSaveClick(int productId)
        {
            List<ActivityProduct> list = SaveProductIntoDB(productId);
            return View(list);
        }
     

        public ActionResult GetSavedProds()
        {
            List<ActivityProduct> list = GetSavedProducts();
            return View(list);
        }

        public List<ActivityProduct> GetSavedProducts()
        {
            string url = "http://localhost:49896";

            List<ActivityProduct> activityProduct = new List<ActivityProduct>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Activity/GetSavedItems").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);
                }
            }
            return activityProduct;

        }

        public ActionResult GetBookedProds()
        {
            List<ActivityProduct> list = GetBookedProducts();
            return View(list);
        }
        public List<ActivityProduct> GetBookedProducts()
        {
            string url = "http://localhost:49896";

            List<ActivityProduct> activityProduct = new List<ActivityProduct>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Activity/GetBookedItems").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ActivityProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<ActivityProduct>>(ActivityProductResponse);
                }
            }

ProductBookinUI/ProductBookinUI/Views/Activity/AddActivityProduct.cshtml
@model ProductBookinUI.Models.ActivityProduct

@{
    
    ViewBag.Title = "Welcome Admin --- Insert Activity Product here!";
}

<h2>AddActivityProduct</h2>

 
@using (Html.BeginForm("AddProductIntoDB", "Activity", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ActivityProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FromTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
            </div>
        </div>
         
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProductBookinUI/ProductBookinUI/Views/Activity/GetActivityProducts.cshtml
@model IEnumerable<ProductBookinUI.Models.ActivityProduct>

@{
    ViewBag.Title = "Activity Products";
}

<h2>GetActivityProducts</h2>

<p> 
    @Html.ActionLink("Get Saved Items", "GetSavedProds")
</p>
<p>@Html.ActionLink("Get Booked Items", "GetBookedProds")</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Place)
        </td>
       
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id})  
        </td>
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Activity/GetBookedProds.cshtml
@model IEnumerable<ProductBookinUI.Models.ActivityProduct>

@{
    ViewBag.Title = "GetBookedProds";
}

<h2>GetBookedProds</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th> 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Place)
        </td> 
        
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Activity/GetSavedProds.cshtml
@model IEnumerable<ProductBookinUI.Models.ActivityProduct>

@{
    ViewBag.Title = "GetSavedProds";
}

<h2>GetSavedProds</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Place)
        </td>
       
       
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Activity/OnBookClick.cshtml
@model IEnumerable<ProductBookinUI.Models.ActivityProduct>

@{
    ViewBag.Title = "OnBookClick";
}

<h2>OnBookClick</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th> 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Place)
        </td> 
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id }) 
        </td>
    </tr>
}

</table>
@if (ViewData["CantBook"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("Cant book");
        };
    </script>
}

ProductBookinUI/ProductBookinUI/Views/Activity/OnSaveClick.cshtml
@model IEnumerable<ProductBookinUI.Models.ActivityProduct>

@{
    ViewBag.Title = "OnSaveClick";
}

<h2>OnSaveClick</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th>
     
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Place)
        </td>
       
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id })
            
        </td>
    </tr>
}

</table>
@if (ViewData["CantSave"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("Cant book");
        };
    </script>
}