ProductBookinUI/ProductBookinUI/Controllers/HotelController.cs
using Newtonsoft.Json;
using ProductBookinUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ProductBookinUI.Controllers
{
    public class HotelController : Controller
    {
        // GET: Hotel
        public ActionResult GetHotelProducts()
        {
            List<HotelProduct> list = GetHotelProductsList();

            return View(list);
        }

        public List<HotelProduct> GetHotelProductsList()
        {
            string url = "http://localhost:49896";

            List<HotelProduct> hotelProduct = new List<HotelProduct>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Hotel").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string HotelProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<HotelProduct>>(HotelProductResponse);

                }
            }
            return hotelProduct;
        }

        public List<HotelProduct> AddProductIntoDB(HotelProduct Product)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                Product.isBooked = false;
                Product.isSaved = false;
                var httpContent = new StringContent(JsonConvert.SerializeObject(Product), Encoding.UTF8, "application/json");

                HttpResponseMessage response = client.PostAsync("/api/Hotel", httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<HotelProduct>>(ProductResponse);

                }
            }
            return null;
        }

        public ActionResult AddHotelProduct()
        {
            return View();
        }

        public List<HotelProduct> SaveProductIntoDB(int productId)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var httpContent = new StringContent(JsonConvert.SerializeObject(productId), Encoding.UTF8, "application/json");

                List<HotelProduct> list = GetHotelProductsList();
                HotelProduct dummy = list.Find(item => item.Id == productId);
                if (dummy.isBooked == true)
                    ViewData["CantBook"] = "true";


                HttpResponseMessage response = client.PutAsync("/api/Hotel/Save/" + productId, httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    JsonConvert.DeserializeObject<List<HotelProduct>>(ProductResponse); 
                }
                HttpResponseMessage response1 = client.GetAsync("/api/Hotel").Result;
                if (response1.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response1.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<HotelProduct>>(ProductResponse);
                }
            }
            return null;
        }
        public ActionResult OnBookClick(int productId)
        {
            List<HotelProduct> list = BookProductIntoDB(productId);
            return View(list);
        }

        public ActionResult OnSaveClick(int productId)
        {
            List<HotelProduct> list = SaveProductIntoDB(productId);
            return View(list);
        }

        public List<HotelProduct> BookProductIntoDB(int productId)
        {

            string url = "http://localhost:49896";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var httpContent = new StringContent(JsonConvert.SerializeObject(productId), Encoding.UTF8, "application/json");

                List<HotelProduct> list = GetHotelProductsList();
                HotelProduct dummy = list.Find(item => item.Id == productId);
                if (dummy.isSaved == true)
                    ViewData["CantSave"] = "true";

                HttpResponseMessage response = client.PutAsync("/api/Hotel/Book/" + productId, httpContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    JsonConvert.DeserializeObject<List<HotelProduct>>(ProductResponse); 
                }
                HttpResponseMessage response1 = client.GetAsync("/api/Hotel").Result;
                if (response1.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response1.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<HotelProduct>>(ProductResponse);
                }
            }
            return null;
        }
        public ActionResult GetSavedProds()
        {
            List<HotelProduct> list = GetSavedProducts();
            return View(list);
        }

        public List<HotelProduct> GetSavedProducts()
        {
            string url = "http://localhost:49896";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Hotel/GetSavedItems").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<HotelProduct>>(ProductResponse);
                }
            }
            return null;

        }

        public ActionResult GetBookedProds()
        {
            List<HotelProduct> list = GetBookedProducts();
            return View(list);
        }
        public List<HotelProduct> GetBookedProducts()
        {
            string url = "http://localhost:49896";


            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("/api/Hotel/GetBookedItems").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    string ProductResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    return JsonConvert.DeserializeObject<List<HotelProduct>>(ProductResponse);
                }
            }
            return null;

        }
    }
}

ProductBookinUI/ProductBookinUI/Views/Hotel/AddHotelProduct.cshtml
@model ProductBookinUI.Models.HotelProduct

@{
    ViewBag.Title = "AddHotelProduct";
}

<h2>AddHotelProduct</h2>

@using (Html.BeginForm("AddProductIntoDB", "Hotel", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HotelProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Name</label>
        @*    @Html.LabelFor(model => model.LandMark, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.LandMark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LandMark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProductBookinUI/ProductBookinUI/Views/Hotel/GetBookedProds.cshtml
@model IEnumerable<ProductBookinUI.Models.HotelProduct>

@{
    ViewBag.Title = "GetBookedProds";
}

<h2>GetBookedProds</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LandMark)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th> 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LandMark)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>  
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Hotel/GetHotelProducts.cshtml
@model IEnumerable<ProductBookinUI.Models.HotelProduct>

@{
    ViewBag.Title = "GetHotelProducts";
}

<h2>GetHotelProducts</h2>
<p>
    @Html.ActionLink("Get Saved Items", "GetSavedProds")
</p>
<p>@Html.ActionLink("Get Booked Items", "GetBookedProds")</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            <p>Name </p>
            @*   @Html.DisplayNameFor(model => model.LandMark)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
    
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LandMark)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
   
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id })
        </td>
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Hotel/GetSavedProds.cshtml
@model IEnumerable<ProductBookinUI.Models.HotelProduct>

@{
    ViewBag.Title = "GetSavedProds";
}

<h2>GetSavedProds</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            <p>Name </p>
            @*   @Html.DisplayNameFor(model => model.LandMark)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th> 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LandMark)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td> 
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Hotel/OnBookClick.cshtml
@model IEnumerable<ProductBookinUI.Models.HotelProduct>

@{
    ViewBag.Title = "OnBookClick";
}

<h2>OnBookClick</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)

        </th>
        <th>
            <p>Name </p>
         @*   @Html.DisplayNameFor(model => model.LandMark)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LandMark)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id })
        </td>
    </tr>
}

</table>

ProductBookinUI/ProductBookinUI/Views/Hotel/OnSaveClick.cshtml
@model IEnumerable<ProductBookinUI.Models.HotelProduct>

@{
    ViewBag.Title = "OnSaveClick";
}

<h2>OnSaveClick</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            <p>Name </p>
            @*   @Html.DisplayNameFor(model => model.LandMark)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LandMark)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        
        <td>
            @Html.ActionLink("Book", "OnBookClick", new { @productId = item.Id }) |
            @Html.ActionLink("Save", "OnSaveClick", new { @productId = item.Id })
        </td>
    </tr>
}

</table>